### ISSUE TITLE
Checkpoint 1 - Instructor Notes

### ISSUE THREAD

**Issue by pawaitemadisoncollege** [manderson394/carbConscious#1]
What a meaningful and useful project you are building! Great work on your problem statement.  It's clear you've put some good thought and time into your plan and screen design. I think they will serve you well. 

User stories look good and the MVP seems well-sized. I like the stretch goal - if you do have time to implement, there are several services that would work well for geo-location.

A few questions:

- [x] Are there screens to add/edit/delete menu items?
- [x] Is a user story needed for add/edit/delete a restaurant, or is that part of the menu item? 
- [x] It looks like there is a screen for forgotten uid/pwd - is there a corresponding user story? 
- [x] If you are doing password reset or userid retrieval - an api for email that is pretty easy to implement is JavaMail. That could meet your webservice/api requirement.

**Comment by manderson394** [comment]
Hey @pawaitemadisoncollege,

Thank you for the feedback! I've added the additional user story and the goal to use JavaMail to my project documentation. Users should only need to add carbohydrate information for menu items. The restaurants and menu items are actually grabbed from the menu API, not created by users on the fly. 

I've updated the project with a wire frame to document carbohydrate information editing.
