### ISSUE TITLE
Design Review 1 - Jacob Doney

### ISSUE THREAD

**Issue by jdone934** [manderson394/carbConscious#4]
# Design/Code Review 1

### Reviewer:Jacob Doney

|Item |Considerations| Comments/Suggestions|
|--------|---------|---|
|||Reviewer comments and suggestions go here. Each item should have *at least* one "kudos" and two suggestions for improvement|
|**Problem Statement**|1. Accurately describes project purpose<br> 2. Is professional and free of typos, slang, etc.<br> 3. Fully explains the problem and the solution<br> 4. Is understandable by the average person|Kudos<br>1. The explanation for the motivation behind completing this particular project fells very comprehensive.<br><br>Suggestions<br>1. There could be a little more explanation how you intend to fix the problem.<br>2. Maybe be worth calling out that you are using EC2 for Amazon Web Services.|
|**Design Documentation**|1. Navigation/flow through the application is logical and easy to use. <br>2. The order in which values are displayed are logical and easy to understand/use <br>3. The order in which the form fields entered are logical and easy to understand/use<br>4. All data discussed/documented (problem statement, flow, db design, etc.) is represented on the screens |Kudos<br>1. The screen designs are well laid out very logically and bring the users attention to the right spots.<br>2. Application Flow outlines the project very well.<br><br>Suggestions<br>1. A few of the items in your Application Flow could be fleshed out (i.e, under the 'Contact' section, what happens after the user submits the form? Do they recieve confirmation?)<br>2. I don't see any mention of admin abilities in your design documents. <br>3. Use of more icons may make your site more useable.|
|**Data model/Database**|1. Everything on the screens and problem statement/flow is represented in the model <br> 2. There is at least one 1-to-many relationship.<br> 3. The model represents good database design <br>|Kudos<br>1. Design encompasses the project as it's laid out in the rest of your desgin documents.<br><br>Suggestions<br>1. It's difficult to tell from the diagram, but I belive there to be a many-to-many relationship between 'MENU_ITEMS' and 'USER_FAVORITES'. If this is the case, make sure to utilize an associative table.<br>2. If 'OUTCOMES' is just going to be an id and a name, this likely doesn't need to be it's own table and could just be a value in 'CARBOHYDRATES' |
|**Code**|1. Proper Maven project structure is used<br> 2. a .gitignore file for IntelliJ Java projects has been implemented <br> 3. There is not any redundant or copy/paste code in the JSPs or classes<br> 4. Classes are appropriately-sized (no monster classes)<br> Property files are used appropriately: no hard-coded values <br> 5. Logging statements are used rather than System.out.println and printStackTrace.<br> 6. There are appropriate unit tests/code coverages.|Kudos<br>1. Code is very clean and easy to read. <br>2. Everything is well documented<br><br>Suggestions<br>1. You seem to test a lot of getters and setters. This may be personal preference, but it feels a bit gratuitous to me.<br>2. On line 52 of 'UserRoleTest', you have a line 'assertEquals(1,1)' that should likely be 'assertEquals(1,id)'|

**Comment by manderson394** [comment]
Thanks, @jdone934! I've updated my README.md, added use of icons, planned to add validation to the client pieces, and corrected my UserRoleTest class. I've updated my database tables for OUTCOMES and rectified my many-to-many relationship.
