### ISSUE TITLE
Instructor Feedback

### ISSUE THREAD

**Issue by pawaitemadisoncollege** [manderson394/carbConscious#9]
Hi Matt! You've been doing a nice job working hard on your project throughout the semester and making steady improvements to address any open issues, so there's not much of anything for me to nitpick at this point!

- [x] update readme.md with actual implemented technologies
- [x] I like that you thought to use Utility classes/interfaces for some of that often-used code - be sure to call that out in your presentation.

**Comment by manderson394** [comment]
Thanks, Paula!
